### ISSUE TITLE
[전체] DB 스키마 설계

### ISSUE THREAD

**Issue by HungKungE** [programmers-kdt-full-stack-3rd/community-board#1]
### 1. MVP 그려보기
먼저, 해당 기능이 동작 할 화면을 그린다.
### 2. MVP 분석
그 화면을 분석해서 기능을 만들기 위해 필요한 것을 파악하고 스키마를 설계한다. 

## ✅ To-Do
- [x] 전체적인 MVP 그리기
- [x] 회원 기능 스키마
- [x] 게시글 기능 스키마
- [x] 댓글 기능 스키마

**Comment by HungKungE** [comment]
https://github.com/programmers-kdt-full-stack-3rd/community-board/commit/91d94b008cd19fe2f5bfeae05d581cd32f2f1ea5
