### ISSUE TITLE
[BE] Q&A 댓글 채택 기능 개발

### ISSUE THREAD

**Issue by jun108059** [programmers-kdt-full-stack-3rd/community-board#230]
## todo
- [ ] qna 테이블 생성
- [ ] qna 게시판 댓글 채택 기능 추가
- [ ] qna 게시판 댓글 채택 정보 조회 기능 추가

## 참조
[명세 문서](https://www.notion.so/prgrms/7ee97ce06e76402ebf05312c1b02de60?pvs=4)
